// Toyland Product Catalog & Initial State Data
const TOYLAND_CATEGORIES = [
  { id: 'soft-toys', name: 'Soft Toys', emoji: '🧸', icon: 'fa-paw', count: 24, desc: 'Ultra-soft cuddly companions & plushies', img: 'https://images.unsplash.com/photo-1559454403-b8fb88521f11?auto=format&fit=crop&w=600&q=80', color: '#FFE8EC' },
  { id: 'rc-toys', name: 'Remote Control Toys', emoji: '🚗', icon: 'fa-car-side', count: 18, desc: 'High-speed RC cars, trucks & drones', img: 'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?auto=format&fit=crop&w=600&q=80', color: '#E8F4FD' },
  { id: 'puzzles', name: 'Puzzles & Games', emoji: '🧩', icon: 'fa-puzzle-piece', count: 32, desc: 'Brain-teasers, jigsaws & wooden puzzles', img: 'https://images.unsplash.com/photo-1589254065878-42c9da997008?auto=format&fit=crop&w=600&q=80', color: '#FEF3D6' },
  { id: 'building-blocks', name: 'Building Blocks', emoji: '🧱', icon: 'fa-cubes', count: 29, desc: 'Creative bricks, magnetic tiles & towers', img: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=600&q=80', color: '#E7F9F0' },
  { id: 'arts-crafts', name: 'Arts & Crafts', emoji: '🎨', icon: 'fa-palette', count: 21, desc: 'Coloring, DIY craft kits & pottery sets', img: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=600&q=80', color: '#F6E8FF' },
  { id: 'dolls', name: 'Dolls & Doll Houses', emoji: '🪆', icon: 'fa-child-dress', count: 19, desc: 'Dream mansions, fashion dolls & accessories', img: 'https://images.unsplash.com/photo-1560963689-02e82017fb3c?auto=format&fit=crop&w=600&q=80', color: '#FFEBF3' },
  { id: 'educational', name: 'Educational Toys', emoji: '🚀', icon: 'fa-brain', count: 27, desc: 'STEM sets, robotics & interactive discovery', img: 'https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=600&q=80', color: '#E5F6FF' },
  { id: 'outdoor', name: 'Outdoor Toys', emoji: '⚽', icon: 'fa-futbol', count: 23, desc: 'Scooters, sporting sets, blasters & games', img: 'https://images.unsplash.com/photo-1535572292327-11f3b04c8f52?auto=format&fit=crop&w=600&q=80', color: '#E8FAEA' },
  { id: 'kids-games', name: 'Kids Games', emoji: '🎮', icon: 'fa-gamepad', count: 16, desc: 'Family board games, arcade fun & card decks', img: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=600&q=80', color: '#FFF3E0' },
  { id: 'action-figures', name: 'Action Figures', emoji: '🦖', icon: 'fa-dragon', count: 22, desc: 'Superheroes, dinosaurs & legendary warriors', img: 'https://images.unsplash.com/photo-1608889825103-eb5ed706fc64?auto=format&fit=crop&w=600&q=80', color: '#FBE9E7' },
  { id: 'baby-toys', name: 'Baby Toys', emoji: '👶', icon: 'fa-baby', count: 15, desc: 'Non-toxic teethers, rattles & sensory mats', img: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=600&q=80', color: '#FFF8E1' },
  { id: 'gifts', name: 'Gifts & Hampers', emoji: '🎁', icon: 'fa-gift', count: 35, desc: 'Curated celebration sets & birthday wonders', img: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=600&q=80', color: '#F3E5F5' }
];

const TOYLAND_COLLECTIONS = [
  {
    id: 'learning-growing',
    title: 'Learning & Growing',
    subtitle: 'Educational toys that make learning fun.',
    img: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=700&q=80',
    tag: 'STEM & Brain Play',
    theme: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
    categoryFilter: 'educational'
  },
  {
    id: 'adventure-zone',
    title: 'Adventure Zone',
    subtitle: 'Cars, action figures, dinosaurs and exciting adventure toys.',
    img: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=700&q=80',
    tag: 'Thrill & Action',
    theme: 'linear-gradient(135deg, #ff9966 0%, #ff5e62 100%)',
    categoryFilter: 'action-figures'
  },
  {
    id: 'little-creators',
    title: 'Little Creators',
    subtitle: 'Arts, crafts, drawing and creative toys.',
    img: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=700&q=80',
    tag: 'Creativity & DIY',
    theme: 'linear-gradient(135deg, #b174fa 0%, #e072f8 100%)',
    categoryFilter: 'arts-crafts'
  },
  {
    id: 'outdoor-fun',
    title: 'Outdoor Fun',
    subtitle: 'Toys and games for active outdoor play.',
    img: 'https://images.unsplash.com/photo-1535572292327-11f3b04c8f52?auto=format&fit=crop&w=700&q=80',
    tag: 'Active Play',
    theme: 'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)',
    categoryFilter: 'outdoor'
  },
  {
    id: 'cuddle-corner',
    title: 'Cuddle Corner',
    subtitle: 'Cute and soft plush toys.',
    img: 'https://images.unsplash.com/photo-1559454403-b8fb88521f11?auto=format&fit=crop&w=700&q=80',
    tag: 'Fluffy Companions',
    theme: 'linear-gradient(135deg, #ff9a9e 0%, #fecfef 99%, #fecfef 100%)',
    categoryFilter: 'soft-toys'
  },
  {
    id: 'game-night',
    title: 'Game Night',
    subtitle: 'Board games, puzzles and family games.',
    img: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=700&q=80',
    tag: 'Family Fun',
    theme: 'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
    categoryFilter: 'kids-games'
  }
];

const TOYLAND_PRODUCTS = [
  // 12 Best Sellers
  {
    id: 1,
    name: 'Thunder Drift RC Racing Car 4WD',
    category: 'rc-toys',
    categoryName: 'Remote Control Toys',
    price: 1499,
    originalPrice: 2499,
    rating: 4.9,
    reviewsCount: 142,
    age: '6–8 Years',
    ageGroup: '6-8',
    isBestSeller: true,
    isNew: false,
    tag: 'Boys',
    image: 'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?auto=format&fit=crop&w=600&q=80',
    description: 'High-speed rechargeable drift car with 2.4GHz remote control, realistic LED headlamps, 360-degree spins, and rugged anti-skid tires.',
    features: ['High speed 25 km/h', 'Dual motor 4WD', 'Rechargeable Li-Ion battery', 'Shockproof chassis']
  },
  {
    id: 2,
    name: 'Jumbo Fluffy Cuddle Teddy Bear (3 Feet)',
    category: 'soft-toys',
    categoryName: 'Soft Toys',
    price: 1299,
    originalPrice: 1999,
    rating: 5.0,
    reviewsCount: 289,
    age: '0–2 Years',
    ageGroup: '0-2',
    isBestSeller: true,
    isNew: false,
    tag: 'Baby',
    image: 'https://images.unsplash.com/photo-1559454403-b8fb88521f11?auto=format&fit=crop&w=600&q=80',
    description: 'Silky-soft plush teddy bear made with hypoallergenic polyester stuffing, stitched safety eyes, and a charming satin bow.',
    features: ['100% Non-Toxic & Washable', 'Super huggable 3-foot height', 'Child-safe embedded eyes', 'Soft premium micro-velvet']
  },
  {
    id: 3,
    name: 'MagnoCraft 100-Piece 3D Magnetic Tiles',
    category: 'building-blocks',
    categoryName: 'Building Blocks',
    price: 1799,
    originalPrice: 2999,
    rating: 4.8,
    reviewsCount: 176,
    age: '3–5 Years',
    ageGroup: '3-5',
    isBestSeller: true,
    isNew: false,
    tag: 'Educational',
    image: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=600&q=80',
    description: 'Translucent kaleidoscopic magnetic geometric building blocks that stimulate spatial imagination, architectural thinking, and creativity.',
    features: ['Strong neodymium magnets', 'Food-grade BPA-free plastic', 'Rounded edges for safety', 'Includes wheels & idea book']
  },
  {
    id: 4,
    name: 'Little Medic Deluxe Pediatrician Kit (18 Pcs)',
    category: 'educational',
    categoryName: 'Educational Toys',
    price: 899,
    originalPrice: 1399,
    rating: 4.7,
    reviewsCount: 98,
    age: '3–5 Years',
    ageGroup: '3-5',
    isBestSeller: true,
    isNew: false,
    tag: 'Educational',
    image: 'https://images.unsplash.com/photo-1584447128309-b66b7a4d1b63?auto=format&fit=crop&w=600&q=80',
    description: 'Realistic pretend-play doctor suitcase with flashing heartbeat stethoscope, otoscope, thermometer, and sturdy carrying box.',
    features: ['Electronic sounds & pulse lights', 'Durable smooth plastic', 'Portable handle kit', 'Helps overcome fear of doctors']
  },
  {
    id: 5,
    name: 'T-Rex Roar & Walk Interactive Dinosaur',
    category: 'action-figures',
    categoryName: 'Action Figures',
    price: 1349,
    originalPrice: 2199,
    rating: 4.9,
    reviewsCount: 165,
    age: '6–8 Years',
    ageGroup: '6-8',
    isBestSeller: true,
    isNew: false,
    tag: 'Boys',
    image: 'https://images.unsplash.com/photo-1608889825103-eb5ed706fc64?auto=format&fit=crop&w=600&q=80',
    description: 'Ferocious Tyrannosaurus Rex with realistic textured skin, moving jaw, glowing crimson eyes, mist spray breath, and thrilling sound effects.',
    features: ['Simulated water-mist roar', 'Movable joints & realistic stride', 'Dynamic lighting effect', 'Durable non-toxic ABS']
  },
  {
    id: 6,
    name: 'Nordic Montessori Wooden Jigsaw & Clock Puzzle',
    category: 'puzzles',
    categoryName: 'Puzzles & Games',
    price: 699,
    originalPrice: 1199,
    rating: 4.8,
    reviewsCount: 112,
    age: '3–5 Years',
    ageGroup: '3-5',
    isBestSeller: true,
    isNew: false,
    tag: 'Baby',
    image: 'https://images.unsplash.com/photo-1589254065878-42c9da997008?auto=format&fit=crop&w=600&q=80',
    description: 'Eco-friendly natural wood sorting puzzle board with counting numbers, geometric shape pegs, and an interactive learning clock.',
    features: ['100% sustainably sourced wood', 'Smooth splinter-free polish', 'Water-based organic paints', 'Develops fine motor control']
  },
  {
    id: 7,
    name: 'Fairytale Princess Villa 3-Story Dollhouse',
    category: 'dolls',
    categoryName: 'Dolls & Doll Houses',
    price: 2499,
    originalPrice: 3999,
    rating: 4.9,
    reviewsCount: 204,
    age: '3–5 Years',
    ageGroup: '3-5',
    isBestSeller: true,
    isNew: false,
    tag: 'Girls',
    image: 'https://images.unsplash.com/photo-1560963689-02e82017fb3c?auto=format&fit=crop&w=600&q=80',
    description: 'Multilevel open-concept mansion equipped with 4 decorated rooms, balcony, staircase, 2 posable mini-dolls, and 14 pieces of miniature furniture.',
    features: ['Sturdy wooden & plastic frame', 'Includes LED fairy lights', 'Fully furnished rooms', 'Encourages narrative storytelling']
  },
  {
    id: 8,
    name: 'SparkleStudio 80-Piece Kids Art & Drawing Case',
    category: 'arts-crafts',
    categoryName: 'Arts & Crafts',
    price: 949,
    originalPrice: 1599,
    rating: 4.7,
    reviewsCount: 88,
    age: '6–8 Years',
    ageGroup: '6-8',
    isBestSeller: true,
    isNew: false,
    tag: 'Girls',
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=600&q=80',
    description: 'Deluxe art studio suitcase including washable watercolor markers, vibrant oil pastels, acrylics, sketch crayons, eraser, and drawing pad.',
    features: ['Washable non-toxic pigments', 'Portable wooden case latch', 'Dual-tip color pens', 'Ideal birthday craft gift']
  },
  {
    id: 9,
    name: 'SkyFalcon Gyro RC Dual-Rotor Helicopter',
    category: 'rc-toys',
    categoryName: 'Remote Control Toys',
    price: 1899,
    originalPrice: 2899,
    rating: 4.6,
    reviewsCount: 79,
    age: '9–12 Years',
    ageGroup: '9-12',
    isBestSeller: true,
    isNew: false,
    tag: 'Boys',
    image: 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&w=600&q=80',
    description: 'Precision alloy RC helicopter with built-in altitude hold gyroscope, one-key take-off and landing, crash protection, and LED night lights.',
    features: ['Intelligent altitude hover', 'Durable alloy frame', 'One-key return & landing', 'USB fast-charging battery']
  },
  {
    id: 10,
    name: 'RoboBot Coding STEM Smart Companion',
    category: 'educational',
    categoryName: 'Educational Toys',
    price: 2199,
    originalPrice: 3499,
    rating: 4.9,
    reviewsCount: 210,
    age: '6–8 Years',
    ageGroup: '6-8',
    isBestSeller: true,
    isNew: false,
    tag: 'Educational',
    image: 'https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=600&q=80',
    description: 'Interactive STEM robot that teaches early coding fundamentals through card sequences, obstacle avoidance sensors, singing, and voice recording.',
    features: ['Screen-free directional coding', 'Voice recording & playback', 'Obstacle detection sensors', 'Dance & puzzle game modes']
  },
  {
    id: 11,
    name: 'Kingdom Quest Family Fantasy Board Game',
    category: 'kids-games',
    categoryName: 'Kids Games',
    price: 849,
    originalPrice: 1299,
    rating: 4.8,
    reviewsCount: 92,
    age: '9–12 Years',
    ageGroup: '9-12',
    isBestSeller: true,
    isNew: false,
    tag: 'Games',
    image: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=600&q=80',
    description: 'An exciting cooperative family board game of dragon riddles, treasure maps, and strategic castle defense for 2 to 6 players.',
    features: ['Engaging 30-45 min gameplay', 'High-quality tokens & cards', 'Easy to learn rulebook', 'Great for family game nights']
  },
  {
    id: 12,
    name: 'MasterChef Junior Wooden Kitchen Play Center',
    category: 'educational',
    categoryName: 'Educational Toys',
    price: 3299,
    originalPrice: 4999,
    rating: 5.0,
    reviewsCount: 310,
    age: '3–5 Years',
    ageGroup: '3-5',
    isBestSeller: true,
    isNew: false,
    tag: 'Girls',
    image: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&w=600&q=80',
    description: 'Realistic wooden play kitchen with clickable oven knobs, simulated ice dispenser, stainless-steel cookware set, and spice racks.',
    features: ['Realistic clicking sound knobs', 'Includes pans, pots & utensils', 'Chalkboard shopping menu', 'Heavy-duty engineered wood']
  },

  // New Arrivals & Specialized Sections
  {
    id: 13,
    name: 'Nebula Glow 3-Wheel Adjustable Scooter',
    category: 'outdoor',
    categoryName: 'Outdoor Toys',
    price: 1999,
    originalPrice: 2899,
    rating: 4.8,
    reviewsCount: 64,
    age: '3–5 Years',
    ageGroup: '3-5',
    isBestSeller: false,
    isNew: true,
    tag: 'Outdoor',
    image: 'https://images.unsplash.com/photo-1535572292327-11f3b04c8f52?auto=format&fit=crop&w=600&q=80',
    description: 'Smooth-gliding lean-to-steer scooter featuring kinetic LED flashing wheels that light up during motion without batteries.',
    features: ['Height adjustable 4-levels', 'Kinetic magnetic light wheels', 'Extra wide anti-slip deck', 'Rear foot safety brake']
  },
  {
    id: 14,
    name: 'Pro-Kick High Bounce Training Football Size 3',
    category: 'outdoor',
    categoryName: 'Outdoor Toys',
    price: 599,
    originalPrice: 999,
    rating: 4.7,
    reviewsCount: 43,
    age: '6–8 Years',
    ageGroup: '6-8',
    isBestSeller: false,
    isNew: true,
    tag: 'Outdoor',
    image: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=600&q=80',
    description: 'Machine-stitched TPU composite football built for lawn, grass, and outdoor playground action with an included air pump.',
    features: ['All-weather durable casing', 'High retention bladder', 'Free hand pump & pin', 'Vibrant neon easy-track pattern']
  },
  {
    id: 15,
    name: 'Solar System Planetary Orbit Science Projector',
    category: 'educational',
    categoryName: 'Educational Toys',
    price: 1199,
    originalPrice: 1799,
    rating: 4.9,
    reviewsCount: 82,
    age: '6–8 Years',
    ageGroup: '6-8',
    isBestSeller: false,
    isNew: true,
    tag: 'Educational',
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80',
    description: 'Motorized celestial dome projector showcasing 8 revolving planets, starry constellations, and audio cosmic facts narrated in clear English.',
    features: ['Built-in ceiling star projector', 'Touch audio guide buttons', 'Includes constellation dome', 'Operates on AA batteries/USB']
  },
  {
    id: 16,
    name: 'Kawaii Pastel Boba Bunny Hugging Pillow',
    category: 'soft-toys',
    categoryName: 'Soft Toys',
    price: 799,
    originalPrice: 1299,
    rating: 4.9,
    reviewsCount: 153,
    age: '0–2 Years',
    ageGroup: '0-2',
    isBestSeller: false,
    isNew: true,
    tag: 'Baby',
    image: 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?auto=format&fit=crop&w=600&q=80',
    description: 'Irresistibly squishy memory foam plush pillow shaped like a friendly boba tea bunny with embroidered sleepy eyes.',
    features: ['Slow rebound squishy plush', 'Removable machine-washable skin', 'Calming bedtime cuddle buddy', 'Zero plastic loose parts']
  },
  {
    id: 17,
    name: 'CyberMech 4-in-1 Remote Controlled Crawler',
    category: 'rc-toys',
    categoryName: 'Remote Control Toys',
    price: 1699,
    originalPrice: 2599,
    rating: 4.8,
    reviewsCount: 47,
    age: '9–12 Years',
    ageGroup: '9-12',
    isBestSeller: false,
    isNew: true,
    tag: 'Boys',
    image: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=600&q=80',
    description: 'All-terrain rock crawler with independent suspension, climbing capability up to 45 degrees, and modular transformable armor.',
    features: ['High-torque climbing motor', 'Heavy duty rubber tracks', 'Splash-proof water resistance', 'Twin LED spotlights']
  },
  {
    id: 18,
    name: 'Sparkle Slime & Gemstone DIY Magic Cauldron',
    category: 'arts-crafts',
    categoryName: 'Arts & Crafts',
    price: 899,
    originalPrice: 1499,
    rating: 4.6,
    reviewsCount: 71,
    age: '6–8 Years',
    ageGroup: '6-8',
    isBestSeller: false,
    isNew: true,
    tag: 'Girls',
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=600&q=80',
    description: 'Complete glitter potion craft lab with glow powders, scented charms, holographic sequins, and mixing vials for kids.',
    features: ['Safe borax-free formula', '6 potion test bottles', 'Color changing pigments', 'Clean spill-resistant tray']
  },
  {
    id: 19,
    name: 'SpeedCube Pro Carbon Fiber 3x3 Brain Puzzle',
    category: 'puzzles',
    categoryName: 'Puzzles & Games',
    price: 499,
    originalPrice: 799,
    rating: 4.9,
    reviewsCount: 198,
    age: '13+ Years',
    ageGroup: '13+',
    isBestSeller: false,
    isNew: true,
    tag: 'Games',
    image: 'https://images.unsplash.com/photo-1591991731833-b4807cf7ef94?auto=format&fit=crop&w=600&q=80',
    description: 'Smooth magnetic corner-cutting speed cube with textured carbon-fiber stickers and adjustable spring tension for fast solving.',
    features: ['Anti-pop internal mechanism', 'High precision corner cutting', 'Carbon fiber tactile grip', 'Lubricated tournament-ready']
  },
  {
    id: 20,
    name: 'Sensory Musical Soft Mat for Infants',
    category: 'baby-toys',
    categoryName: 'Baby Toys',
    price: 1199,
    originalPrice: 1899,
    rating: 4.9,
    reviewsCount: 115,
    age: '0–2 Years',
    ageGroup: '0-2',
    isBestSeller: false,
    isNew: true,
    tag: 'Baby',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=600&q=80',
    description: 'Kicking piano play gym with overhead arches, dangling sensory rattles, teething ring, and 20 gentle nursery tunes.',
    features: ['Padded thick washable cotton', 'Kicking piano with soothing tunes', 'Detergent-safe fabric', '3 in 1: tummy time, sit & play']
  },
  {
    id: 21,
    name: 'AeroBlast Super Soaker Water Blaster 1200ml',
    category: 'outdoor',
    categoryName: 'Outdoor Toys',
    price: 749,
    originalPrice: 1199,
    rating: 4.7,
    reviewsCount: 56,
    age: '6–8 Years',
    ageGroup: '6-8',
    isBestSeller: false,
    isNew: true,
    tag: 'Outdoor',
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=600&q=80',
    description: 'High-capacity pump-action water blaster shooting up to 32 feet with rapid refill cap and leak-proof seal.',
    features: ['32 feet long-range stream', 'Large 1200ml reservoir', 'Ergonomic non-slip handle', 'Tough drop-proof casing']
  },
  {
    id: 22,
    name: 'Ultimate 100+ Science Experiment Lab Box',
    category: 'educational',
    categoryName: 'Educational Toys',
    price: 1599,
    originalPrice: 2499,
    rating: 4.9,
    reviewsCount: 167,
    age: '9–12 Years',
    ageGroup: '9-12',
    isBestSeller: false,
    isNew: true,
    tag: 'Educational',
    image: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=600&q=80',
    description: 'Packed with real test tubes, volcano mold, safe crystal-growing salts, litmus papers, and an illustrated 64-page guide.',
    features: ['100+ fun experiments', 'Chemical safety goggles included', 'Step-by-step colorful comic manual', 'Encourages scientific thinking']
  }
];

const AGE_GROUPS_DATA = [
  { id: '0-2', label: '0–2 Years', subtitle: 'Babies & Toddlers', img: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=500&q=80', badge: 'Sensory & Safe', color: '#FFF3E0' },
  { id: '3-5', label: '3–5 Years', subtitle: 'Preschoolers', img: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&w=500&q=80', badge: 'Pretend & Build', color: '#E8F5E9' },
  { id: '6-8', label: '6–8 Years', subtitle: 'Curious Explorers', img: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=500&q=80', badge: 'STEM & Action', color: '#E1F5FE' },
  { id: '9-12', label: '9–12 Years', subtitle: 'Creative Innovators', img: 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&w=500&q=80', badge: 'Complex & Robotics', color: '#F3E5F5' },
  { id: '13+', label: '13+ Years', subtitle: 'Teens & Family', img: 'https://images.unsplash.com/photo-1591991731833-b4807cf7ef94?auto=format&fit=crop&w=500&q=80', badge: 'Strategy & Speed', color: '#FBE9E7' }
];
